name: Run Tests

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Check Out Repository
              uses: actions/checkout@v2

            - name: Set Up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Install Dependencies
              run: pnpm install

            - name: Generate Prisma Client
              run: pnpm dlx prisma generate

            - name: Run Tests
              run: pnpm test
